openapi: 3.0.0
info:
  title: Movie Payment API
  version: 1.0.0
  description: Allows users to browse available movies and make payments for movie tickets
paths:
  /movies:
    get:
      summary: Retrieve available movies
      responses:
        '200':
          description: Movies retrieved successfully
          content:
            application/json:
              schema:
                type: array
                items:
                  type: object
                  properties:
                    movieId:
                      type: integer
                      example: 1
                    name:
                      type: string
                      example: "Deadpool & Wolverine"
        '404':
          description: No movies found
  /payment:
    post:
      summary: Submit a movie ticket payment
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                movieId:
                  type: integer
                  example: 1
                customerId:
                  type: integer
                  example: 456
                paymentType:
                  type: string
                  example: "debit_card"
                totalAmount:
                  type: number
                  format: float
                  example: 15.50
      responses:
        '200':
          description: Payment was successfully completed
          content:
            application/json:
              schema:
                type: object
                properties:
                  paymentId:
                    type: string
                    example: "transaction456"
                  result:
                    type: string
                    example: "success"
        '400':
          description: Error in payment processing
          content:
            application/json:
              schema:
                type: object
                properties:
                  errorMessage:
                    type: string
                    example: "Payment method invalid"
  /movies/{id}:
    delete:
      summary: Delete a movie by ID
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: integer
      responses:
        '200':
          description: Movie deleted successfully
        '404':
          description: Movie not found
        '500':
          description: Internal server error

