openapi: 3.0.0
info:
  title: Movie Payment Service API
  version: 1.0.0
paths:
  /movies:
    get:
      summary: Retrieve available movies
      responses:
        '200':
          description: Movies retrieved successfully
          content:
            application/json:
              schema:
                type: array
                items:
                  type: object
                  properties:
                    movieId:
                      type: integer
                      example: 1
                    name:
                      type: string
                      example: "Inception"
  /payment:
    post:
      summary: Submit a movie ticket payment
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                movieId:
                  type: integer
                  example: 1
                customerId:
                  type: integer
                  example: 456
                paymentType:
                  type: string
                  example: "debit_card"
                totalAmount:
                  type: number
                  format: float
                  example: 15.50
      responses:
        '200':
          description: Payment was successfully completed
          content:
            application/json:
              schema:
                type: object
                properties:
                  paymentId:
                    type: string
                    example: "transaction67817181"
                  result:
                    type: string
                    example: "success"
        '400':
          description: Error in payment processing
          content:
            application/json:
              schema:
                type: object
                properties:
                  errorMessage:
                    type: string
                    example: "Payment method invalid"

